from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.CourseListView.as_view(), name='list'),
    # Documents (Instructor upload, Normal Staff library + saved)
    path('documents/', views.DocumentsLibraryView.as_view(), name='documents_library'),
    path('documents/saved/', views.SavedDocumentsView.as_view(), name='saved_documents'),
    path('documents/upload/', views.DocumentUploadView.as_view(), name='document_upload'),
    path('documents/<int:pk>/view/', views.document_view, name='document_view'),
    path('documents/<int:pk>/download/', views.document_download, name='document_download'),
    path('teaching/', views.CourseTeachingListView.as_view(), name='teaching'),
    path('all/', views.CourseAllTableView.as_view(), name='list_all'),
    path('create/', views.CourseCreateView.as_view(), name='create'),
    path('<int:pk>/', views.CourseDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', views.CourseUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.CourseDeleteView.as_view(), name='delete'),
    path('<int:pk>/content/', views.course_content, name='content'),
    path('<int:pk>/content/page/add/', views.course_page_add, name='page_add'),
    path('<int:pk>/content/page/<int:page_pk>/edit/', views.course_page_edit, name='page_edit'),
    path('<int:pk>/content/page/<int:page_pk>/delete/', views.course_page_delete, name='page_delete'),
    path('<int:pk>/content/file/add/', views.course_file_add, name='file_add'),
    path('<int:pk>/content/file/<int:file_pk>/edit/', views.course_file_edit, name='file_edit'),
    path('<int:pk>/content/file/<int:file_pk>/delete/', views.course_file_delete, name='file_delete'),
    path('<int:pk>/content/page/<int:page_pk>/', views.view_page, name='view_page'),
    path('<int:pk>/content/file/<int:file_pk>/', views.download_file, name='download_file'),
    path('<int:pk>/content/section/add/', views.course_section_add, name='section_add'),
    path('<int:pk>/content/section/<int:section_pk>/edit/', views.course_section_edit, name='section_edit'),
    path('<int:pk>/content/section/<int:section_pk>/delete/', views.course_section_delete, name='section_delete'),
    path('<int:pk>/content/section/<int:section_pk>/module/add/', views.course_module_add, name='module_add'),
    path('<int:pk>/content/module/<int:module_pk>/edit/', views.course_module_edit, name='module_edit'),
    path('<int:pk>/content/module/<int:module_pk>/delete/', views.course_module_delete, name='module_delete'),
    path('<int:pk>/submit-for-approval/', views.submit_for_approval, name='submit_for_approval'),
    path('pending-approval/', views.CoursePendingApprovalListView.as_view(), name='pending_approval'),
    path('<int:pk>/approve/', views.approve_course, name='approve'),
    path('<int:pk>/reject/', views.reject_course, name='reject'),
    path('<int:pk>/return/', views.return_course_for_revision, name='return_for_revision'),
    path('<int:pk>/announcements/', views.course_announcements_list, name='announcements_list'),
    path('<int:pk>/announcements/add/', views.course_announcement_add, name='announcement_add'),
    path('<int:pk>/analytics/', views.course_analytics, name='analytics'),
    path('<int:pk>/reports/export/', views.course_export_reports, name='export_reports'),
    path('<int:pk>/certificates/', views.course_certificates, name='certificates'),
    path('<int:pk>/certificates/issue/<int:user_pk>/', views.course_certificate_issue, name='certificate_issue'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='category'),
    path('categories/manage/', views.CategoryManageListView.as_view(), name='categories_manage'),
    path('categories/manage/create/', views.category_create, name='category_create'),
    path('categories/manage/<int:pk>/edit/', views.category_edit, name='category_edit'),
    path('categories/manage/<int:pk>/deactivate/', views.category_deactivate, name='category_deactivate'),
]
