# Generated by Django 4.2.29 on 2026-03-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_set_existing_courses_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If set, guests can download this file without registering (publicly released study material).'),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='is_preview',
            field=models.BooleanField(default=False, help_text='If set, guests can view this lesson without registering (instructor-designated preview).'),
        ),
    ]
