# Generated by Django 4.2.29 on 2026-03-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_preview_and_public_guest_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefile',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='coursepage',
            name='is_preview',
        ),
    ]
