# Generated by Django 4.2.29 on 2026-03-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceroom',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Session duration in minutes (e.g. 120 for 2 hours, 300 for 5 hours).', null=True),
        ),
    ]
