# Generated by Django 4.2.29 on 2026-03-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_type',
            field=models.CharField(blank=True, choices=[('dpa', 'DPA Student (Diploma in Police Administration)'), ('normal_staff', 'Normal Staff (Police officers – training materials access)')], help_text='For students: DPA program or Normal Staff (training materials only).', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Instructor'), ('moderator', 'Moderator'), ('admin', 'Administrator')], default='student', max_length=20),
        ),
    ]
