# Generated by Django 4.2.29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_student_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_code',
            field=models.CharField(
                blank=True,
                help_text='Unique staff identifier for Instructors/Moderators (e.g., service/employee number).',
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]

