# Generated by Django 4.2.29 on 2026-03-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_staff_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_teach',
            field=models.BooleanField(default=False, help_text='If True, user can create and manage courses (instructor capability). Moderators can have this to also act as instructors; instructors have it via role=teacher.'),
        ),
    ]
