# Generated by Django 4.2.29 on 2026-03-09 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_alter_course_enrollment_type'),
        ('enrollment', '0003_remove_study_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_list_entries', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_list_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'elening_study_list',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
