# Generated by Django 4.2.29 on 2026-03-10 08:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='rubric_criteria',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Marking rubric: criteria and point breakdown for grading.'),
        ),
    ]
